devwards/apps/main/urls.py
from django.conf.urls import url

from . import views 

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

devwards/apps/users/urls.py
from django.conf.urls import url
from .views import RegisterView, LoginView, LogoutView

urlpatterns = [
	url(r'^registrar/$', RegisterView.as_view(), name='register'),
	url(r'^ingresar/$', LoginView.as_view(), name='login'),
	url(r'^salir/$', LogoutView.as_view(), name='logout'),
]

devwards/apps/webs/urls.py
from django.conf.urls import url

from. import views

urlpatterns = [
	url(r'^sitios/enviar/$', views.send_website, name='send'),
	url(r'^sitios/(?P<slug>[-\w]+)/$', views.website_vote),
	url(r'^sitios/(?P<slug>[-\w]+)/votar/$', views.website_detail)
]

devwards/devwards/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.main.urls', namespace='main')),
    url(r'^', include('apps.users.urls', namespace='users')),
    url(r'^', include('apps.webs.urls', namespace='webs')),
    url(r'^admin/', admin.site.urls),
]

devwards/apps/users/models.py
from django.db import models

devwards/apps/webs/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.

class WebSite(models.Model):

	nombre = models.CharField(max_length=100)
	slug = models.SlugField(editable=False)
	url = models.URLField()
	description = models.CharField(max_length=100)
	designer = models.CharField(max_length=100)
	designer_url = models.URLField()
	twitter = models.CharField(max_length=100)
	image1 = models.ImageField(upload_to = 'websites')
	image2 = models.ImageField(upload_to = 'websites')
	image3 = models.ImageField(upload_to = 'websites')

	create_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name)
		super(WebSite, self).save(*args, **kwargs)

devwards/apps/users/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ('username', 'email', 'password')
		widgets = {
			'username' : forms.TextInput(attrs={
				'type' : 'text',
				'placeholder' : 'Username'
				}),
			'email' : forms.TextInput(attrs={
				'type' : 'email',
				'placeholder' : 'Email'
				}),
			'password' : forms.TextInput(attrs={
				'type' : 'password',
				'placeholder' : 'Contraseña'
				})
		}


class LoginForm(forms.Form):

	username = forms.CharField(max_length=50, widget=forms.TextInput(attrs={
		'type' : 'text',
		'placeholder' : 'Usuario',
		}))

	password = forms.CharField(max_length=50, widget=forms.TextInput(attrs={
		'type' : 'password',
		'placeholder' : 'Contraseña',
		}))


	def clean(self):

		user_found = User.objects.filter(username = self.cleaned_data['username']).exists()
		if not user_found:
			self.add_error('username', 'El usuario no Existe')
		else:
			user = User.objects.get(username = self.cleaned_data['username'])
			if not user.check_password(self.cleaned_data['password']):
				self.add_error('password', 'Password Incorrecto')
		#print(self.cleaned_data)

devwards/apps/main/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home.html')

devwards/apps/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, FormView, View
from .forms import LoginForm, RegisterForm
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth import login, authenticate, logout

# Create your views here.

class LogoutView(View):

	def get(self, request, *args, **kwargs):
		logout(request)
		return redirect(reverse('main:home'))

class RegisterView(FormView):

	template_name = 'register.html'
	form_class = RegisterForm
	success_url = reverse_lazy('main:home')

	def form_valid(self, form):
		user = form.save()
		user.set_password(form.cleaned_data['password'])
		user.save()
		login(self.request, user)
		return super(RegisterView, self).form_valid(form)

class LoginView(FormView):

	template_name = 'login.html'
	form_class = LoginForm
	success_url = reverse_lazy('main:home')
	
	def form_valid(self, form):
		user = authenticate(
				username = form.cleaned_data['username'],
				password = form.cleaned_data['password']
			)
		#print(user)
		login(self.request, user)
		return super(LoginView, self).form_valid(form)

devwards/apps/webs/views.py
from django.shortcuts import render

# Create your views here.

def send_website(request):
	return render(request, 'enviar-sitio.html')

def website_detail(request, slug):
	return render(request, 'detalle.html')

def website_vote(request, slug):
	return render(request, 'vote.html')

devwards/apps/main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>{% block title %}DevWards{% endblock title %}</title>

	{% load static from staticfiles %}
	<link rel="stylesheet" href="{% static 'css/fonts.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>

	{% block styles %}
	
	{% endblock styles %}
</head>
<body>

	{% block header %}
		<header class="head">
		<div class="background-white">
			<div class="container">
				<div class="head__one  row between middle">
					<span class="head__one__item">
						Los premios para el diseño, la creatividad y la innovación en Internet
					</span>
					{% if user.is_authenticated %}
						<span>Hola, {{ user.username }}</span>
						<a class="head__one__item-a head__one__item-a--bold" href="{% url 'users:logout' %}">Logout</a>
					{% else %}
						<ul class="row middle">
						<li class="head__one__item">
							<a class="head__one__item-a">¿Eres miembro?</a>
						</li>
						<li class="head__one__item ">
							<a class="head__one__item-a head__one__item-a--bold" href="{% url 'users:register' %}">Registrar</a>
							<a class="head__one__item-a head__one__item-a--bold" href="{% url 'users:login' %}">Iniciar sesión</a>
						</li>
					</ul>
					{% endif %}
				</div>	
			</div>
		</div>
		<div class="background-gray border__bottom-gray shadow__menu">
			<div class="container">
				<div class="head__two row between middle">
					<span class="head__two__item--logo">devwards</span>
					<ul class="row middle">
						<li class="head__two__item">
							<a class="head__two__item-a" href="{% url 'main:home' %}">home</a>
						</li>
						<li class="head__two__item">
							<a class="head__two__item-a" href="">nosotros</a>
						</li>
						<li class="head__two__item">
							<a class="head__two__item-a head__two__item-a--button" href="{% url 'webs:send' %}">enviar tu sitio</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</header>
	{% endblock header %}

	{% block content %}

	{% endblock content %}

	<script src="{% static 'js/vendor/jquery.js' %}"></script>
	<script src="{% static 'js/vendor/chart.js' %}"></script>
	{% block scripts %}

	{% endblock scripts %}
</body>
</html>

devwards/apps/main/templates/home.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block title %}
	DevWards
{% endblock title %}

{% block content %}
	<section class="background-gray">
		<div class="container--1000">
			<article class="site__main row middle">
				<div class="site__main-section--left">
					<figure class="site__main-section__figure">
						<a href="">
							<img src="{% static 'img/site1.jpg' %}" alt="">
						</a>
					</figure>
				</div>
				<div class="site__main-section--right">
					<div class="site__main-section--header">
						<span>Lunes 17, Octubre</span>
						<h2>Descubre tus Patrones</h2>
						<p>By <strong>Active Theory</strong> from <strong>U.S.A.</strong></p>
					</div>
					<div class="site__main-section--notes row middle between">
						<div class="site__main-section--notes--item row column">
							<canvas class="site__main-section--notes-circle" id="myChart1" width="50" height="50"></canvas>
							<span class="site__main-section--notes--item__percent">7.90</span>
							<p class="site__main-section--notes--item__name">Diseño</p>
						</div>
						<div class="site__main-section--notes--item row column">
							<canvas class="site__main-section--notes-circle" id="myChart2" width="180" height="180"></canvas>
							<span class="site__main-section--notes--item__percent">7.90</span>
							<p class="site__main-section--notes--item__name">Usabilidad</p>
						</div>
						<div class="site__main-section--notes--item row column">
							<canvas class="site__main-section--notes-circle" id="myChart3" width="180" height="180"></canvas>
							<span class="site__main-section--notes--item__percent">7.90</span>
							<p class="site__main-section--notes--item__name">Creatividad</p>
						</div>
						<div class="site__main-section--notes--item row column">
							<canvas class="site__main-section--notes-circle" id="myChart4" width="180" height="180"></canvas>
							<span class="site__main-section--notes--item__percent">7.90</span>
							<p class="site__main-section--notes--item__name">Contenido</p>
						</div>
					</div>
					<div class="site__main-section--jury">
						<div class="row middle around">
							<img src="{% static 'img/persona1.jpg' %}" alt="">
							<img src="{% static 'img/persona2.jpg' %}" alt="">
							<img src="{% static 'img/persona3.jpg' %}" alt="">
						</div>
					</div>
				</div>
			</article>
			<article class="site__content row column">
				<p class="site__content__title">Estos son los siguientes nominados</p>
				<ul class="site__content__nominateds row wrap between">
					<li class="site__content__nominated">
						<figure class="site__content__nominated--figure">
							<img src="{% static 'img/site1.jpg' %}" alt="">
						</figure>
						<div class="row column">
							<div class="site__content__nominated-head">
								<h4 class="site__content__nominated--title">Houston Ballet</h4>
								<p class="site__content__nominated--description">By Adage Technologies from U.S.A.</p>
							</div>
							<div class="site__content__nominated-footer row middle between">
								<span class="site__content__nominated--score">7.76</span>
								<a class="site__content__nominated--button">Votar</a>
							</div>
						</div>
					</li>
					<li class="site__content__nominated">
						<figure class="site__content__nominated--figure">
							<img src="{% static 'img/site1.jpg' %}" alt="">
						</figure>
						<div class="row column">
							<div class="site__content__nominated-head">
								<h4 class="site__content__nominated--title">Houston Ballet</h4>
								<p class="site__content__nominated--description">By Adage Technologies from U.S.A.</p>
							</div>
							<div class="site__content__nominated-footer row middle between">
								<span class="site__content__nominated--score">7.76</span>
								<a class="site__content__nominated--button">Votar</a>
							</div>
						</div>
					</li>
					<li class="site__content__nominated">
						<figure class="site__content__nominated--figure">
							<img src="{% static 'img/site1.jpg' %}" alt="">
						</figure>
						<div class="row column">
							<div class="site__content__nominated-head">
								<h4 class="site__content__nominated--title">Houston Ballet</h4>
								<p class="site__content__nominated--description">By Adage Technologies from U.S.A.</p>
							</div>
							<div class="site__content__nominated-footer row middle between">
								<span class="site__content__nominated--score">7.76</span>
								<a class="site__content__nominated--button">Votar</a>
							</div>
						</div>
					</li>
					<li class="site__content__nominated">
						<figure class="site__content__nominated--figure">
							<img src="{% static 'img/site1.jpg' %}" alt="">
						</figure>
						<div class="row column">
							<div class="site__content__nominated-head">
								<h4 class="site__content__nominated--title">Houston Ballet</h4>
								<p class="site__content__nominated--description">By Adage Technologies from U.S.A.</p>
							</div>
							<div class="site__content__nominated-footer row middle between">
								<span class="site__content__nominated--score">7.76</span>
								<a class="site__content__nominated--button">Votar</a>
							</div>
						</div>
					</li>
					<li class="site__content__nominated">
						<figure class="site__content__nominated--figure">
							<img src="{% static 'img/site1.jpg' %}" alt="">
						</figure>
						<div class="row column">
							<div class="site__content__nominated-head">
								<h4 class="site__content__nominated--title">Houston Ballet</h4>
								<p class="site__content__nominated--description">By Adage Technologies from U.S.A.</p>
							</div>
							<div class="site__content__nominated-footer row middle between">
								<span class="site__content__nominated--score">7.76</span>
								<a class="site__content__nominated--button">Votar</a>
							</div>
						</div>
					</li>
					<li class="site__content__nominated">
						<figure class="site__content__nominated--figure">
							<img src="{% static 'img/site1.jpg' %}" alt="">
						</figure>
						<div class="row column">
							<div class="site__content__nominated-head">
								<h4 class="site__content__nominated--title">Houston Ballet</h4>
								<p class="site__content__nominated--description">By Adage Technologies from U.S.A.</p>
							</div>
							<div class="site__content__nominated-footer row middle between">
								<span class="site__content__nominated--score">7.76</span>
								<a class="site__content__nominated--button">Votar</a>
							</div>
						</div>
					</li>
				</ul>
			</article>
		</div>
	</section>
	<footer class="footer">
		<div class="background-white">
			<span class="footer-icon icon-twitter"></span>
			<span class="footer-icon icon-facebook"></span>
			<span class="footer-icon footer-icon--heart icon-heart"></span>
			<span class="footer-icon icon-google-plus"></span>
			<span class="footer-icon icon-vimeo"></span>
		</div>
	</footer>
{% endblock content %}	

{% block scripts %}
	<script>
		var data1 = [
			{
				value: 90,
				color: "#3673D9"
			}, 
			{
				value: 10,
				color: "#0095FF"
			}
		];
		var data2 = [
			{
				value: 90,
				color: "#D0021B"
			}, 
			{
				value: 10,
				color: "#0095FF"
			}
		];
		var data3 = [
			{
				value: 90,
				color: "#F5A623"
			}, 
			{
				value: 10,
				color: "#0095FF"
			}
		];

		var data4 = [
			{
				value: 90,
				color: "#7ED321"
			}, 
			{
				value: 10,
				color: "#0095FF"
			}
		];

		var options = {
			responsive: true,
			animation: false,
			percentageInnerCutout : 75
		};

		var c1 = $('#myChart1');
		var c2 = $('#myChart2');
		var c3 = $('#myChart3');
		var c4 = $('#myChart4');

		var ct1 = c1.get(0).getContext('2d');
		var ct2 = c2.get(0).getContext('2d');
		var ct3 = c3.get(0).getContext('2d');
		var ct4 = c4.get(0).getContext('2d');

		var ctx1 = document.getElementById("myChart1").getContext("2d");
		myNewChart1 = new Chart(ct1).Doughnut(data1, options);

		var ctx2 = document.getElementById("myChart2").getContext("2d");
		myNewChart2 = new Chart(ct2).Doughnut(data2, options);

		var ctx3 = document.getElementById("myChart3").getContext("2d");
		myNewChart3 = new Chart(ct3).Doughnut(data3, options);

		var ctx4 = document.getElementById("myChart4").getContext("2d");
		myNewChart4 = new Chart(ct4).Doughnut(data4, options);
	</script>
{% endblock scripts %}

devwards/apps/users/templates/login.html
{% extends "base.html" %}

{% block content %}
	<section class="background-gray">
		<div class="container--600">
			<div class="site__register row column">
				<h1>Login</h1>
				<p><i>Ingresa con tu facebook o twitter</i></p>
				<div class="site__register__button row middle between">
					<a class="site__register__button-fb" href="">
						Login con Facebook
					</a>
					<a class="site__register__button-tw" href="">
						Login con Twitter
					</a>
				</div>
				<p><i>o ingresa con tu Usuario y contraseña</i></p>
				<form class="site__form background-white" method="POST">
					{% csrf_token %}
					<div class="site__form__input">
						{{ form.username }}
						{{ form.username.errors }}
						{{ form.password }}
						{{ form.password.errors }}
						<input type="submit" value="Enviar">
					</div>
				</form>
				<p class="site__register__link">¿Aún no eres miembro? <a href="">Registrate ahora</a></p>
			</div>
		</div>
	</section>
	<footer class="footer">
		<div class="background-white">
			<span class="footer-icon icon-twitter"></span>
			<span class="footer-icon icon-facebook"></span>
			<span class="footer-icon footer-icon--heart icon-heart"></span>
			<span class="footer-icon icon-google-plus"></span>
			<span class="footer-icon icon-vimeo"></span>
		</div>
	</footer>
{% endblock content %}

devwards/apps/users/templates/register.html
{% extends "base.html" %}

{% block content %}
	<section class="background-gray">
		<div class="container--600">
			<div class="site__register row column">
				<h1>Registro</h1>
				<div class="site__register__button row middle between">
					<a class="site__register__button-fb" href="">
						Registro con Facebook
					</a>
					<a class="site__register__button-tw" href="">
						Registro con Twitter
					</a>
				</div>
				<p><i>o create una cuenta con tu Usuario y Contraseña</i></p>
				<form class="site__form background-white" method="POST">
					{% csrf_token %}
					<div class="site__form__input">
						{{ form.username }}
						{{ form.username.errors }}
						{{ form.email }}
						{{ form.email.errors }}
						{{ form.password }}
						{{ form.password.errors }}
						<input type="submit" value="Enviar">
					</div>
				</form>
				<p class="site__register__link">¿Ya eres miembro? <a href="">Ingresar ahora</a></p>
			</div>
		</div>
	</section>
	<footer class="footer">
		<div class="background-white">
			<span class="footer-icon icon-twitter"></span>
			<span class="footer-icon icon-facebook"></span>
			<span class="footer-icon footer-icon--heart icon-heart"></span>
			<span class="footer-icon icon-google-plus"></span>
			<span class="footer-icon icon-vimeo"></span>
		</div>
	</footer>
{% endblock content %}

devwards/apps/webs/templates/detalle.html
{% extends "base.html" %}
{% load static from staticfiles %}
	<!--<header class="head">
		<div class="background-white">
			<div class="container">
				<div class="head__one  row between middle">
					<span class="head__one__item">
						Los premios para el diseño, la creatividad y la innovación en Internet
					</span>
					<ul class="row middle">
						<li class="head__one__item">
							<a class="head__one__item-a">¿Eres miembro?</a>
						</li>
						<li class="head__one__item ">
							<a class="head__one__item-a head__one__item-a--bold" href="">Registrar / Iniciar sesión</a>
						</li>
					</ul>
				</div>	
			</div>
		</div>
		<div class="background-gray border__bottom-gray shadow__menu">
			<div class="container">
				<div class="head__two row between middle">
					<span class="head__two__item--logo">devwards</span>
					<ul class="row middle">
						<li class="head__two__item">
							<a class="head__two__item-a" href="">home</a>
						</li>
						<li class="head__two__item">
							<a class="head__two__item-a" href="">nosotros</a>
						</li>
						<li class="head__two__item">
							<a class="head__two__item-a head__two__item-a--button" href="">enviar tu sitio</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</header>-->
{% block header %}
	<header class="head-login">
		<div class="background-gray border__bottom-gray shadow__menu">
			<div class="container">
				<div class="head__two row between middle">
					<span class="head__two__item--logo">devwards</span>
					<ul class="row middle">
						<li class="head__two__item">
							<a class="head__two__item-a" href="{% url 'main:home' %}">home</a>
						</li>
						<li class="head__two__item">
							<a class="head__two__item-a" href="">nosotros</a>
						</li>
						<li class="head__two__item">
							<a class="head__two__item-a head__two__item-a--user">JulioGrados</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</header>
{% endblock header %}
{% block content %}
	<section class="background-gray">
		<div class="container--1000">
			<article class="site__detail--main row middle between">
				<div class="site__detail--main__left">
					<span>Lunes 17, Octubre</span>
					<h2>Descubre tus Patrones</h2>
					<p>By <strong>Active Theory</strong> from <strong>U.S.A.</strong></p>
					<p class="site__detail--main__left-description">The experience transports users into a 3D environment where those taking part will make a series of choices based on a set of cryptic prompts, eventually discovering their Patronus.</p>
				</div>
				<div class="site__detail--main__rigth row column">
					<div class="site__detail--main__rigth-vote row column center">
						<a class="site__button" href="">Votar ahora</a>
					</div>
					<div class="site__main-section--notes row middle between">
						<div class="site__main-section--notes--item row column">
							<canvas class="site__main-section--notes-circle" id="myChart1" width="50" height="50"></canvas>
							<span class="site__main-section--notes--item__percent">7.90</span>
							<p class="site__main-section--notes--item__name">Diseño</p>
						</div>
						<div class="site__main-section--notes--item row column">
							<canvas class="site__main-section--notes-circle" id="myChart2" width="180" height="180"></canvas>
							<span class="site__main-section--notes--item__percent">7.90</span>
							<p class="site__main-section--notes--item__name">Usabilidad</p>
						</div>
						<div class="site__main-section--notes--item row column">
							<canvas class="site__main-section--notes-circle" id="myChart3" width="180" height="180"></canvas>
							<span class="site__main-section--notes--item__percent">7.90</span>
							<p class="site__main-section--notes--item__name">Creatividad</p>
						</div>
						<div class="site__main-section--notes--item row column">
							<canvas class="site__main-section--notes-circle" id="myChart4" width="180" height="180"></canvas>
							<span class="site__main-section--notes--item__percent">7.90</span>
							<p class="site__main-section--notes--item__name">Contenido</p>
						</div>
					</div>
				</div>
			</article>
			<article class="site__detail--images">
				<img class="site__detail--images__figure" src="{% static 'img/site1.jpg' %}" alt="">
				<img class="site__detail--images__figure" src="{% static 'img/site1.jpg' %}" alt="">
				<img class="site__detail--images__figure" src="{% static 'img/site1.jpg' %}" alt="">
			</article>
			<article class="site__detail--authors row middle between">
				<div class="site__detail--author row column">
					<div class="row middle">
						<figure class="site__detail--author__figure">
							<img src="{% static 'img/persona1.jpg' %}" alt="">
						</figure>
						<div class="site__detail--author__name row column">
							<h4>Juan Jose Pino</h4>
							<span>dcamilleri.com</span>
						</div>
					</div>
					<p class="site__detail--author__description">Front-end Developer at Firstborn. JavaScript developer @wisembly and @Get_Solid.</p>
				</div>
				<div class="site__detail--author row column">
					<div class="row middle">
						<figure class="site__detail--author__figure">
							<img src="{% static 'img/persona1.jpg' %}" alt="">
						</figure>
						<div class="site__detail--author__name row column">
							<h4>Juan Jose Pino</h4>
							<span>dcamilleri.com</span>
						</div>
					</div>
					<p class="site__detail--author__description">Front-end Developer at Firstborn. JavaScript developer @wisembly and @Get_Solid.</p>
				</div>
				<div class="site__detail--author row column">
					<div class="row middle">
						<figure class="site__detail--author__figure">
							<img src="{% static 'img/persona1.jpg' %}" alt="">
						</figure>
						<div class="site__detail--author__name row column">
							<h4>Juan Jose Pino</h4>
							<span>dcamilleri.com</span>
						</div>
					</div>
					<p class="site__detail--author__description">Front-end Developer at Firstborn. JavaScript developer @wisembly and @Get_Solid.</p>
				</div>
			</article>
		</div>
	</section>
	<footer class="footer">
		<div class="background-white">
			<span class="footer-icon icon-twitter"></span>
			<span class="footer-icon icon-facebook"></span>
			<span class="footer-icon footer-icon--heart icon-heart"></span>
			<span class="footer-icon icon-google-plus"></span>
			<span class="footer-icon icon-vimeo"></span>
		</div>
	</footer>
{% endblock content %}
{% block scripts %}
	<script>
		var data1 = [
			{
				value: 90,
				color: "#3673D9"
			}, 
			{
				value: 10,
				color: "#0095FF"
			}
		];
		var data2 = [
			{
				value: 90,
				color: "#D0021B"
			}, 
			{
				value: 10,
				color: "#0095FF"
			}
		];
		var data3 = [
			{
				value: 90,
				color: "#F5A623"
			}, 
			{
				value: 10,
				color: "#0095FF"
			}
		];

		var data4 = [
			{
				value: 90,
				color: "#7ED321"
			}, 
			{
				value: 10,
				color: "#0095FF"
			}
		];

		var options = {
			responsive: true,
			animation: false,
			percentageInnerCutout : 75
		};

		var c1 = $('#myChart1');
		var c2 = $('#myChart2');
		var c3 = $('#myChart3');
		var c4 = $('#myChart4');

		var ct1 = c1.get(0).getContext('2d');
		var ct2 = c2.get(0).getContext('2d');
		var ct3 = c3.get(0).getContext('2d');
		var ct4 = c4.get(0).getContext('2d');

		var ctx1 = document.getElementById("myChart1").getContext("2d");
		myNewChart1 = new Chart(ct1).Doughnut(data1, options);

		var ctx2 = document.getElementById("myChart2").getContext("2d");
		myNewChart2 = new Chart(ct2).Doughnut(data2, options);

		var ctx3 = document.getElementById("myChart3").getContext("2d");
		myNewChart3 = new Chart(ct3).Doughnut(data3, options);

		var ctx4 = document.getElementById("myChart4").getContext("2d");
		myNewChart4 = new Chart(ct4).Doughnut(data4, options);
	</script>
{% endblock scripts %}